import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RAVI
 */
public class Delivery_Form extends javax.swing.JFrame {
    int i_no=0;
     Connection con=null;
    PreparedStatement pst=null;
  Statement st=null,stDelete=null;
   ResultSet rs = null;
   java.util.Date date;
   DefaultTableModel  dml;
   private Vector<Vector<String>> data;
        private Vector<String> header;
   //java.sql.Date sqldate;
    /**
     * Creates new form Delivery_Form
     */
    public Delivery_Form()  {
        
       // con= re.getCon();
             // initComponents();
             try {        
              st=con.createStatement();
              rs=st.executeQuery("select * from Customer_Master");
              while(rs.next())
              {
                  jc1.addItem(""+rs.getString(2));                   
              }
                  } catch (Exception ex) {
            System.out.println(ex);
        }
  try {      // con= re.getCon(); 
              st=con.createStatement();
              rs=st.executeQuery("select * from Item_Master");
              while(rs.next())
              {
                  jc2.addItem(""+rs.getString(2));
                   
              }
                  } catch (Exception ex) {
           Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
                    //  System.out.println(ex);
        } 
         java.util.Date d = new java.util.Date();
               String curDate = "";
               

     
  /*     DateFormat df=null;
      
       df=DateFormat.getDateInstance(DateFormat.SHORT);
         String s1= df.format(d);
                
       d1.setText(""+s1);*/
               
    /*             Delievery dce = new Delievery("select * from delievery");
       data = dce.getData();
       
       header = new Vector<String>();
       header.add("Cust_no");
       header.add("Cust Name");
       header.add("Contact");
       header.add("Date");
       header.add("Item");
       header.add("Quantity");  
       header.add("Total");
       */
               
     //  initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jc1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        c_no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cont = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jc2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        DD = new javax.swing.JTable();
        nt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        in = new javax.swing.JTextField();
        dc1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        sbn = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        d1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jInternalFrame1.setVisible(true);

        jLabel1.setText("DELIEVERY FORM");

        jLabel2.setText("Name");

        jc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Customer Name" }));
        jc1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jc1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jc1FocusLost(evt);
            }
        });
        jc1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jc1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jc1MouseClicked(evt);
            }
        });
        jc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Customer No");

        c_no.setEditable(false);
        c_no.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setText("Contact");

        cont.setEditable(false);
        cont.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setText("Current Date");

        jLabel6.setText("Item ");

        jc2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Item" }));
        jc2.setToolTipText("");
        jc2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jc2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jc2FocusLost(evt);
            }
        });
        jc2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jc2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jc2MouseClicked(evt);
            }
        });
        jc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantity");

        qty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyFocusLost(evt);
            }
        });

        DD.setModel(new javax.swing.table.DefaultTableModel(
            data,header
        ));
        jScrollPane2.setViewportView(DD);

        jLabel8.setText("Total");

        jButton1.setText("SAVE");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");

        jLabel9.setText("Rate");

        rate.setEditable(false);
        rate.setBackground(new java.awt.Color(255, 255, 204));

        jLabel10.setText("Item No");

        in.setEditable(false);
        in.setBackground(new java.awt.Color(255, 255, 204));

        dc1.setDateFormatString("yyyy/MM/dd");
        dc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dc1MouseClicked(evt);
            }
        });

        jLabel11.setText("SEARCH BY NAME");

        sbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sbnKeyReleased(evt);
            }
        });

        jLabel12.setText("SEARCH BY DATE");

        jLabel13.setText("FROM");

        jLabel14.setText("TO");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_no, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jc1, 0, 199, Short.MAX_VALUE)
                                                .addComponent(jc2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(cont))
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(18, 18, 18)
                                                .addComponent(in))
                                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(36, 36, 36)
                                                .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(127, 127, 127)))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(295, 295, 295))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(189, 189, 189)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sbn, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel14)
                        .addContainerGap())))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(98, 98, 98))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {

            pst=con.prepareStatement("insert into delievery values(?,?,?,?,?,?,?)");
            System.out.println("keep going");
            pst.setString(1,""+c_no.getText());
            System.out.println("keep going 1");
            pst.setString(2,""+jc1.getSelectedItem());
            System.out.println("keep going 2");
            pst.setString(3,""+cont.getText());
            System.out.println("keep going 3");
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
//Date date = new Date();
          /*  String Date = dateFormat.format(d1.getText());
           SimpleDateFormat s=new SimpleDateFormat("MM-dd-yyyy");
            date=dc1.getDate();
            //sqldate=new java.sql.Date(date.getTime());
           // System.out.println(""+d1);
            d1.setText(s.format(dc1.getDate()));*/
           // pst.setDate(4, java.sql.Date.valueOf(d1.getText()));
//            pst.setString(4,""+d1.getText());
           
            
              //  pst.setString(4, d1.getText());
            SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
             date=dc1.getDate();
               d1.setText(s.format(dc1.getDate()));
            pst.setString(4, ((JTextField)dc1.getDateEditor().getUiComponent()).getText());
           // String date=s.format(dc1.getDate());
           // pst.setString(4, d1.getText());
            System.out.println("keep going 4");
            pst.setString(5,""+jc2.getSelectedItem());
            System.out.println("keep going 5");
            // pst.setString(6,""+tel.getText());
            //pst.setString(7,""+eid.getText());
            pst.setString(6,""+qty.getText());
            System.out.println("keep going 6");
            pst.setString(7,""+nt.getText());
            // pst.setString(10,""+stex.getText());
            jButton1.setEnabled(true);  System.out.println("keep going 7");

            pst.executeUpdate();
 System.out.println("keep going 8");
            JOptionPane.showMessageDialog(null, "Record Inserted Sucessfully....");

            c_no.setText("");
            cont.setText("");
            qty.setText("");
            nt.setText("");
            /* rs=st.executeQuery("select max(Customer_no)from Customer_Master");

            rs.next();
            if(rs!=null)
            {
                i_no=rs.getInt(1);
                i_no++;
            }
            else
            i_no=1;

            id.setText(""+i_no);*/
            

          //  con.close();
          //    jc1.removeAllItems();
          //  jc2.removeAllItems();
        }
        catch(Exception ex)
        {
            System.out.print(ex);
        }                               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void qtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyFocusLost
        int rr=Integer.parseInt(rate.getText());
        int qtyy=Integer.parseInt(qty.getText());
        int ntt=rr*qtyy;
        nt.setText(""+ntt);
    }//GEN-LAST:event_qtyFocusLost

    private void qtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyFocusGained

    }//GEN-LAST:event_qtyFocusGained

    private void jc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc2ActionPerformed
       String s1=(String)jc2.getSelectedItem();
        String sql="select * from Item_Master where Item_name=?";
        try
        {
            pst=con.prepareStatement(sql);
            pst.setString(1,s1);
            rs=pst.executeQuery();
            while(rs.next())
            {
                String i_n=rs.getString("Item_no");
                in.setText(i_n);
                String R=rs.getString("Item_Rate");
                rate.setText(R);

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jc2ActionPerformed

    private void jc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jc2MouseClicked
     /*      try {      // con= re.getCon(); 
             // jc2.removeAll();
              st=con.createStatement();
              rs=st.executeQuery("select * from Item_Master");
              if(rs.next())
              {
                  jc2.addItem(""+rs.getString(2));
               //   jc2.removeAllItems();
              }
                  } catch (Exception ex) {
           Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
                    //  System.out.println(ex);
        }*/
    /*    String s1=(String)jc1.getSelectedItem();
        String sql="select * from Item_Master where Item_name=?";
        try
        {
            pst=con.prepareStatement(sql);
            pst.setString(1,s1);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String i_n=rs.getString("Item_no");
                in.setText(i_n);
                String R=rs.getString("Item_Rate");
                rate.setText(R);

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        */
    }//GEN-LAST:event_jc2MouseClicked

    private void jc2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jc2PopupMenuWillBecomeInvisible
        /*       String s1=(String)jc1.getSelectedItem();
        String sql="select * from Item_Master where Item_name=?";
        try
        {
            pst=con.prepareStatement(sql);
            pst.setString(1,s1);
            rs=pst.executeQuery();
            if(rs.next())
            {
                String i_n=rs.getString("Item_no");
                in.setText(i_n);
                String R=rs.getString("Item_Rate");
                rate.setText(R);

            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }

        */
    }//GEN-LAST:event_jc2PopupMenuWillBecomeInvisible

    private void jc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc1ActionPerformed
        String s1=(String)jc1.getSelectedItem();
        String sql="select * from Customer_Master where Customer_name=?";
        try
        {
            pst=con.prepareStatement(sql);
            pst.setString(1,s1);
            rs=pst.executeQuery();
            while(rs.next()) {
                String cno=rs.getString("Customer_no");
                c_no.setText(cno);
                String con_no=rs.getString("Customer_add3");
                cont.setText(con_no);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jc1ActionPerformed

    private void jc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jc1MouseClicked
        //rrrr  con= re.getCon();
     /*     try {     
          
              st=con.createStatement();
              rs=st.executeQuery("select * from Customer_Master");
              if(rs.next())
              {
                  jc1.addItem(""+rs.getString(2));   
                   
              }
                  } catch (Exception ex) {
            System.out.println(ex);
        }*/
         /*   String s1=(String)jc1.getSelectedItem();
        String sql="select * from Customer_Master where Customer_name="+s1;
        try
        {
            st = con.createStatement();
            rs = st.executeQuery(sql);
            if(rs.next())
            {
                String cno=rs.getString("Customer_no");
                c_no.setText(cno);
                String con_no=rs.getString("Customer_add3");
                cont.setText(con_no);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    */
    }//GEN-LAST:event_jc1MouseClicked

    private void jc1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jc1PopupMenuWillBecomeInvisible

        /*            System.out.println("working");

        try
        {   String sql="select * from Customer_Master where Customer_name=?";

            System.out.println("in progress 1");
            pst=con.prepareStatement(sql);
            String s1=(String)jc1.getSelectedItem();
            pst.setString(1,s1);
            System.out.println("in progress 2");
            rs=pst.executeQuery();
            System.out.println("in progress 2.1");
            while(rs.next()) {
                System.out.println("in progress 3");
                String cno=rs.getString("Customer_no");
                c_no.setText(cno);
                String con_no=rs.getString("Customer_add3");
                cont.setText(con_no);
                System.out.println("in progress 4");
            }
        }
        catch(Exception e)
        {   System.out.println("in progress catch part");
            System.out.println(e);
        }

        /*          String s1=(String)jc1.getSelectedItem();
        String sql="select * from Customer_Master where Customer_name="+s1;
        try
        {  con= re.getCon();
            //  pst=con.prepareStatement(sql);
            // pst.setString(1,s1);
            //rs=pst.executeQuery();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            /*    String SQL = "SELECT * FROM shopkeeper";
            String SQL1 = "SELECT * FROM item";
            stmt = con.createStatement();

            // Steps to extract sportss id and name
            rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                String sID = rs.getString("Shopper_id");
                String Sname = rs.getString("Name");
                sModel.addElement(sID + " - " + Sname);
            }*/
            /*  System.out.println("working");
            if(rs.next())
            {
                String cno=rs.getString("Customer_no");
                c_no.setText(cno);
                String con_no=rs.getString("Customer_add3");
                cont.setText(con_no);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }   */
    }//GEN-LAST:event_jc1PopupMenuWillBecomeInvisible

    private void jc1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jc1FocusLost
 //jc1.removeAllItems();
    }//GEN-LAST:event_jc1FocusLost

    private void jc1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jc1FocusGained
     /*  try {     
          
              st=con.createStatement();
              rs=st.executeQuery("select * from Customer_Master");
              if(rs.next())
              {
                  jc1.addItem(""+rs.getString(2));   
                   
              }
                  } catch (Exception ex) {
            System.out.println(ex);
        }*/
    }//GEN-LAST:event_jc1FocusGained

    private void jc2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jc2FocusGained
     /*     try {      // con= re.getCon(); 
             // jc2.removeAll();
              st=con.createStatement();
              rs=st.executeQuery("select * from Item_Master");
              if(rs.next())
              {
                  jc2.addItem(""+rs.getString(2));
               //   jc2.removeAllItems();
              }
                  } catch (Exception ex) {
           Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
                    //  System.out.println(ex);
        }*/
    }//GEN-LAST:event_jc2FocusGained

    private void jc2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jc2FocusLost
  //       jc2.removeAllItems();
    }//GEN-LAST:event_jc2FocusLost

    private void dc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dc1MouseClicked
  /*     DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
//Date date = new Date();
            String Date = dateFormat.format(d1.getText());
           SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
            date=dc1.getDate();
            //sqldate=new java.sql.Date(date.getTime());
           // System.out.println(""+d1);
            d1.setText(s.format(dc1.getDate()));*/
    }//GEN-LAST:event_dc1MouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
   /*    DefaultTableModel model = (DefaultTableModel) DD.getModel();
        // Clear the existing table
        int rows = model.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                model.removeRow(0);
            }
        }
        // SQL Query
        String query = "SELECT * FROM delievery";
        try {
            ResultSet rs = st.executeQuery(query);

            // Iterate through the result and display on screen
            while (rs.next()) {
                String c_no = rs.getString("cust_no");               
                String c_name = rs.getString("cust_name");
                String c_add = rs.getString("contact");
                String c_phone = rs.getString("curr_date");
                String date=rs.getString("item");
                String c_city=rs.getString("quantity");
                String ntt=rs.getString("total");
                System.out.println(c_no + "|" + c_name + "|" + c_add + "|" + c_phone + "|" + date + "|"+ c_city + "|"+ ntt);
                model.addRow(new Object[] {c_no, c_name, c_add, c_phone,date,c_city,ntt});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }*/
    }//GEN-LAST:event_formWindowGainedFocus

    private void sbnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sbnKeyReleased
        int f=0; 
    
   String s=sbn.getText();
    String s1=null;
        
    for(int i=0;i<s.length();i++)
    {
    
      char a=s.charAt(i);  
       Character chr=new Character(a);
       
      if(chr.isDigit(a))
      {
           f=1;
        s1=s.substring(0, i);   
      }
    }
    if(f==1)
    {
        JOptionPane.showMessageDialog(null,"number not allowed");
     sbn.setText(s1);
    
    }

    try {
                
           
                 Delievery dce = new Delievery("select * from delievery where cust_name like '"+sbn.getText().trim()+"%'");
                 data = dce.getData();
                 header = new Vector<String>();
       header.add("Cust No");
       header.add("Cust Name");
       header.add("Contact");
       header.add("Current Date");
       header.add("Item");
       header.add("Quantity");
       header.add("Total");
      DD.setModel(new javax.swing.table.DefaultTableModel(data,header));         
        } catch (Exception ex) {
            Logger.getLogger(Delivery_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sbnKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  /*      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delivery_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delivery_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delivery_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delivery_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          //      new Delivery_Form().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DD;
    private javax.swing.JTextField c_no;
    private javax.swing.JTextField cont;
    private javax.swing.JTextField d1;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private com.toedter.calendar.JDateChooser dc1;
    private javax.swing.JTextField in;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jc1;
    private javax.swing.JComboBox jc2;
    private javax.swing.JTextField nt;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField sbn;
    // End of variables declaration//GEN-END:variables
}
